### ISSUE TITLE
I made some cool changes! Click here if u don't want to get rickrolled!

### ISSUE THREAD

**Issue by testbot123-cmd** [alonefx/EYE-Music#6]
hope u like them :D
https://github.com/SudhanPlayz/Discord-MusicBot
![image](https://user-images.githubusercontent.com/80935271/123090685-12044100-d446-11eb-9cf6-8599c3e84702.png)
![image](https://user-images.githubusercontent.com/80935271/123090719-1af51280-d446-11eb-8860-c68915c3a616.png)

https://www.youtube.com/watch?v=p4lP96Tiv9s
THIS HAS MORE VIEWS THAN YOURS HAHAHAHA

https://discord.com/invite/a9SHDpD

Give credits and do not claim as it is your own made bot!!

**Comment by testbot123-cmd** [comment]
@sudhanplayz

**Comment by SudhanPlayz** [comment]
> @SudhanPlayz

wut u want

**Comment by testbot123-cmd** [comment]
> > @SudhanPlayz
> 
> wut u want

nothing this guy copied without credits

**Comment by testbot123-cmd** [comment]
nvm he gave credits
